spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_ENDPOINT}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs
      client:
        registration:
          userStoreClient:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
        provider:
          userStoreClient:
            token-uri: ${KEYCLOAK_ENDPOINT}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token

app:
  # AKTIN or DSF or MOCK
  broker-client: ${BROKER_CLIENT_TYPE}

userstore:
  url: ${KEYCLOAK_ENDPOINT}/auth/admin/realms/${KEYCLOAK_REALM}

de:
  num-codex:
    FeasibilityGuiBackend:
      aktin:
        broker:
          baseUrl: ${AKTIN_BROKER_BASE_URL}
          apiKey: ${AKTIN_BROKER_API_KEY}
